spring:
  application:
    profiles:
      active: test
  datasource:
    url: jdbc:mysql://localhost:3307/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6380